### ISSUE TITLE
Registration: SecC Team

### ISSUE THREAD

**Issue by gernst** [verifythis/verifythis.github.io#1]
* Name: SecC Team
* Affiliation: LMU Munich, University of Melbourne
* Contact: Gidon Ernst <gidon.ernst@lmu.de>
* Participants: Gidon Ernst <gidon.ernst@lmu.de>, Toby Murray <toby.murray@unimelb.edu.au>
* Are you a student, (post)-doctoral group?
  Toby is a senior lecturer at the University of Melbourne. Gidon is an junior professor at LMU.

* Webpage(s):
  * https://covern.org/secc/
  * https://github.com/gernst/verifythis2020

* Description:
SecC is a verifier for low-level systems code written in C. SecC supports expressive annotations for value-dependent security classifications to prove information flow security.

* Collaboration: We are looking for feedback and collaboration!

**Comment by wadoon** [comment]
Welcome on board. I have added you to the list of [participants](https://verifythis.github.io/registration/).
