### ISSUE TITLE
VerCors team registration

### ISSUE THREAD

**Issue by raulmonti** [verifythis/verifythis.github.io#2]
* Name:  VerCors
* Affiliation: FMT - University of Twente
* Contact: Raul Monti <r.e.monti@utwente.nl>
* Participants: Raul Monti, Marieke Huisman, Wytze Oortwijn, Sebastiaan Joosten, Sophie Lathouwers, Fauzia Ehsan, Mohsen Safari.
* Are you a student, (post)-doctoral group?
* Webpage(s): 
https://utwente-fmt.github.io/vercors/
https://vcs.utwente.nl/source/vt_lt_2020/

* Description: 
We plan to use VerCors separation logic instruments to verify permission concerns on the Server, such as thread safety. 
We also plan to model the server protocol using a model checker such as MCRL2 and then verify that the code follows such protocol by using actions and futures.

* Collaboration:
It would be great to compare our protocol models with other models and discuss about their correctness. Maybe the differences in abstraction would enrich our analysis. Anyone working with futures or history can directly collaborate also and we can interchange opinions and results in this direction. Finally we will like to know if you can make use of our permission based analysis or if you have ideas in how to tackle this issues using other tools.

**Comment by wadoon** [comment]
Groups was added.
