### ISSUE TITLE
create new group Lumos Maxima

### ISSUE THREAD

**Issue by yannickmoy** [verifythis/verifythis.github.io#3]
* Name:    Lumos Maxima
* Affiliation: [ProofInUse joint lab](https://why3.gitlabpages.inria.fr/proofinuse/) between [AdaCore](https://www.adacore.com/) and [Inria](http://toccata.lri.fr/index.fr.html)
* Contact: Yannick Moy (`<lastname>`@adacore.com) and Claude Marché (`<firstname>.<lastname>`@inria.fr) 
* Participants: Claude Marché, Sylvain Dailler, Johannes Kanig, Claire Dross, Yannick Moy
* Are you a student, (post)-doctoral group? no
* Webpage(s): https://github.com/AdaCore/Lumos_Maxima

* Description: 

Our objective is to redevelop HAGRID in [SPARK](https://github.com/AdaCore/spark2014/), a subset of the Ada programming language targeted at formal verification, and to prove the following properties about the code:
- absence of runtime errors
- correct data and information flows
- functional correctness
- security (privacy?) properties that can be encoded in data/control contracts

We also plan to evaluate the efficiency of the executable code to compare it with the original  implementation in Rust, and to demonstrate its usability on a variety of hardware platforms.

* Collaboration:
 
We are interested in collaborating on the best approach to achieve the above goals, either with people willing to contribute to the project directly, or with people sharing the same overall goals with other languages and tools.

**Comment by wadoon** [comment]
Welcome on board. I've added your group to [the list.](https://verifythis.github.io/registration/).
