### ISSUE TITLE
SMACK Team

### ISSUE THREAD

**Issue by zvonimir** [verifythis/verifythis.github.io#5]
* Name: SMACK Team
* Affiliation: University of Utah
* Contact: Zvonimir Rakamaric, zvonimir@cs.utah.edu
* Participants: TBD
* Webpage(s): http://smackers.github.io/

* Description: Our plan is to try to apply our SMACK software verifier on the target application. SMACK works at the level of LLVM IR, and hence there are interesting challenges in terms of handling LLVM IR produced by the Rust compiler. We also expect that modeling the environment will be challenging as well. Unlike other tools, SMACK is a bounded verifier in its default mode.

* Collaboration: We are eager to collaborate on formalizing the specs and environment for the server.

**Comment by wadoon** [comment]
Welcome on board. I have added you to the [registration page](https://verifythis.github.io/registration/).
